version: "3"
services:
  web:
    image: markojerkic/drumre:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drumre
    ports:
      - 5173:3000
    depends_on:
      - drumre-mongodb
    environment:
      - DATABASE_URL=mongodb://drumre-mongodb:27017
      - DATABASE_NAME=${DATABASE_NAME}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - NY_TIMES_API_KEY=${NY_TIMES_API_KEY}
      - NY_TIMES_API_SECRET=${NY_TIMES_API_SECRET}
      - TRAKT_API_CLIENT_ID=${TRAKT_API_CLIENT_ID}
      - TRAKT_API_CLIENT_SECRET=${TRAKT_API_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - TMDB_API_TOKEN=${TMDB_API_TOKEN}
      - TMDB_API_KEY=${TMDB_API_KEY}
  drumre-mongodb:
    image: mongo:7.0
    container_name: drumre-mongodb
    ports:
      - 27027:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - dbdata:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "38081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_URL=mongodb://drumre-mongodb:27017
    depends_on:
      - drumre-mongodb
volumes:
  dbdata:
